### ISSUE TITLE
Text too difficult to read

### ISSUE THREAD

**Issue by djtravz** [Troop423/troop423.github.io#1]
We could change the background or the text. I don't know where the background file is. I found a good blank picture: [https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSnk1qQh6ZZEDQGId-sS_XlZB8T9z21nSNahjpuMMd2gDUndQuh](url)

**Comment by Troop423** [comment]
changing the text

**Comment by djtravz** [comment]
But the colors vary too much so we might have to change individual words
